spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/shop_spring
    username: postgres
    password: kcv56lk
  flyway:
    baseline-on-migrate: true